# Generated by Django 4.1.7 on 2023-03-04 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_topik_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
