# Generated by Django 4.1.7 on 2023-03-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_topic_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
