# Generated by Django 4.1.7 on 2023-03-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_topic_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='time',
        ),
    ]
