# Generated by Django 4.1.7 on 2023-03-05 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_topic_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
