# Generated by Django 4.1.7 on 2023-03-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(upload_to='avatars')),
            ],
        ),
    ]
