# Generated by Django 4.1.7 on 2023-03-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
