# Generated by Django 4.1.7 on 2023-03-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.FileField(upload_to='avatars'),
        ),
    ]
