# Generated by Django 4.1.7 on 2023-03-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_avatar_id_alter_level_id_alter_like_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='avatar',
            new_name='file',
        ),
    ]
