# Generated by Django 4.1.7 on 2023-03-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_avatar_avatar_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
